const data = {
  products: [
    {
      name: 'comingsoon',
      slug: 'coming-soon',
      category: 'sample cat',
      image: '/images/p1.jpg', // 679px × 829px
      price: 20,
      countInStock: 1,
      brand: 'sample brand',
      rating: 4.5,
      numReviews: 10,
      description: 'sample desc',
    },
    {
      name: 'comingsoon2',
      slug: 'coming-soon-2',
      category: 'sample cat',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 20,
      brand: 'sample brand',
      rating: 4.0,
      numReviews: 10,
      description: 'sample desc',
    },
    {
      name: 'comingsoon3',
      slug: 'coming-soon-3',
      category: 'sampel cat',
      image: '/images/p3.jpg',
      price: 15,
      countInStock: 15,
      brand: 'sample brand',
      rating: 4.5,
      numReviews: 14,
      description: 'sample desc',
    },
    {
      name: 'comingsoon4',
      slug: 'coming-soon-4',
      category: 'sample cat',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'sample brand',
      rating: 4.5,
      numReviews: 10,
      description: 'sample desc',
    },
  ],
};
export default data;
